### ISSUE TITLE
Snap [Feature Request]

### ISSUE THREAD

**Issue by mikeroyal** [luarocks/luarocks#1078]
I was wondering if you might have an interest in a [snap](https://snapcraft.io/) version. I would help make the snap and submit a PR if there's any interest.
[Crafting your first snap](https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0)

**Comment by daurnimator** [comment]
Snap's normal confinement doesn't make sense for a package manager like luarocks. Why would anyone want to install luarocks via snap?

**Comment by hishamhm** [comment]
@mikeroyal Would it be possible to keep LuaRocks inside the snap but the rocks trees outside?

**Comment by mikeroyal** [comment]
Hi @hishamhm, I would need to double check but I do believe that would be possible if that's what you want.

**Comment by hishamhm** [comment]
@mikeroyal I think that's what would make more sense to users. 

Does the snap file have to live in the main repository or can it be a separate repo? If possible, I'd rather not add distribution-specific stuff in the main repo (especially for distribution formats we don't use ourselves, so we have no way to test and maintain). If you're willing to maintain a snap as a separate repo under github.com/luarocks we'd be happy to have it.

**Comment by mikeroyal** [comment]
hi @hishamhm,
Yes, that sounds good. :+1:

**Comment by hishamhm** [comment]
Great — Here's a plan: setup a luarocks-snap repo in your own account, let me know when it's ready and I'll clone it over to github.com/luarocks and give you write access to it. If there's a way to test snaps with CI, all the better!

**Comment by vadi2** [comment]
I'd love a snap version!

**Comment by VilhelmPrytz** [comment]
Any news on this? Would the snap package require the `classic` confinement? If so, it should be fairly easy to create the configuration itself.

This is just a mock-up of how the `snap/snapcraft.yml` could look like (not tested). You could use Travis or [build.snapcraft.io](https://snapcraft.io/build) to build whenever a new commit or release occurs.

```yaml
name: luarocks
base: core18
version: 'v3.2.1'
summary: A short summary of luarocks # 79 char long summary
description: |
  A description of Luarocks!

grade: stable
confinement: classic

parts: # I am not sure how to do this part really, I guess the make plugin is the most appropriate to use for luarocks?
  luarocks:
    plugin: make
    source: .

apps:
  luarocks:
    command: bin/luarocks
```

I would be happy to give it a go, as a pull request perhaps? I reckon you should claim the name `luarocks` before someone else does (I believe you can register it without actually pushing a package).
