### ISSUE TITLE
`No existing manifest. Attempting to rebuild` error during `luarocks --verbose test foo-scm-1.rockspec --prepare` command

### ISSUE THREAD

**Issue by ColinKennedy** [luarocks/luarocks#1731]
I'm trying to get CI working for a Lua / Neovim plugin, using luarocks and for this CI to run on Windows, Linux, and MacOS. Linux and MacOS are fine but Windows errors every time.

Here's an example run: https://github.com/ColinKennedy/mega.vimdoc/actions/runs/12536503432

### Please fill out the following:
- **Platform:**
  - Windows

- **LuaRocks version:**
  - 3.11.0

- **Configuration file:**

```lua
rockspec_format = "3.0"
package = "mega.vimdoc"
version = "scm-1"

local user = "ColinKennedy"

description = {
    homepage = "https://github.com/" .. user .. "/" .. package,
    labels = { "neovim", "neovim-plugin" },
    license = "MIT",
    summary = 'A "Best Practices" Neovim plugin template',
}

source = {
    url = "git://github.com/" .. user .. "/" .. package,
}

build = {
    type = "builtin",
}
```

As you can see there's no dependencies in the .rockspec. This is as close to minimal as I could think to get it.

The test.yml GitHub workflow file:

```yaml
name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
    - main
  push:
    branches:
      - main
      - add_windows_unittests

jobs:
  test:
    strategy:
      matrix:
        neovim: [v0.10.0]
        os: ["windows-latest"]
        luaVersion:
        - "5.1"
        include:
          - os: "windows-latest"
            toolchain: "msvc"
            luaVersion: "5.1"

    runs-on: ${{ matrix.os }}
    name: "OS: ${{ matrix.os }} - Neovim: ${{ matrix.neovim }} - Lua: ${{ matrix.luaVersion }}"

    steps:
    - uses: actions/checkout@master

    - name: Setup MSVC
      # the 'hishamhm/gh-actions-lua' step requires msvc to build PuC Rio Lua
      # versions on Windows (LuaJIT will be build using MinGW/gcc).
      if: ${{ matrix.toolchain == 'msvc' }}
      uses: ilammy/msvc-dev-cmd@v1

    - uses: leafo/gh-actions-lua@master
      with:
        # Neovim is compiled with LuaJIT so we might as well match. But it
        # doesn't look like we can match it exactly.
        #
        # Reference:
        #    https://github.com/leafo/gh-actions-lua/issues/49#issuecomment-2295071198
        #
        luaVersion: "${{ matrix.luaVersion }}"

    - uses: hishamhm/gh-actions-luarocks@v5
      with:
        luarocksVersion: "3.11.0"

    - uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: ${{ matrix.neovim }}

    - name: build
      run: |
        luarocks --verbose test mega.vimdoc-scm-1.rockspec --prepare

    - name: test
      run: |
        luarocks test --test-type busted
```

- **LuaRocks output from when the issue occurred:**
  - Use the `--verbose` flag.

The full log output is too big to paste here. But the relevant bottom error is:

```
2024-12-29T15:13:08.9568932Z No existing manifest. Attempting to rebuild...
2024-12-29T15:13:08.9569448Z 
2024-12-29T15:13:08.9569541Z Error: test suite failed.
2024-12-29T15:13:09.0616844Z ##[error]Process completed with exit code 1.
2024-12-29T15:13:09.0757550Z Post job cleanup.
```

And the full log can be viewed here: https://gist.github.com/ColinKennedy/bdfdf3aa38dd2b70765b98817ec8bb16

- **Reproduction Description:**
```sh
git clone git@github.com:ColinKennedy/mega.vimdoc.git --branch add_windows_unittests
git commit --allow-empty "bump"
git push
```

That triggers the GitHub action which eventually errors

I'm trying to write a generic CI method of installing all dependencies for some luarocks package + its test dependencies and then run the tests. Ideally it'd be something like 

```sh
luarocks --verbose test foo-scm-1.rockspec --prepare
luarocks test --test-type busted
```

Where `foo` is the package name. One Linux and MacOS, the above setup works perfectly. On Windows, it errors before it can get to the `luarocks test --test-type busted` step. As mentioned, I cleared out all dependencies and `luarocks test --prepare ...` still does not run. I've tried a variety of configurations but the all error with `No existing manifest. Attempting to rebuild...` which makes me think the issue is with luarocks itself. Any advice on getting a working solution for Windows that is suitably generic for CI would be appreciated.
