### ISSUE TITLE
LuaRocks fails to install Lua modules written in C on MSYS2 environments which uses clang as default C compiler

### ISSUE THREAD

**Issue by luau-project** [luarocks/luarocks#1753]
### Please fill out the following:
- **Platform:**
  - Windows

- **LuaRocks version:**
  - Even though the version of LuaRocks installed on MSYS2 repositories is 3.9.2, I have confirmed locally that this issue still applies to 3.11.1

- **LuaRocks output from when the issue occurred:**
  It can be clearly seen on the image that LuaRocks invokes gcc rather than clang 

![Image](https://github.com/user-attachments/assets/1d572c74-99c7-48e6-bc9e-d48b7651583c)

- **Description:**

On MSYS2 MinGW-w64 environments using ```clang``` as the C toolchain (```CLANG64``` and ```CLANGARM64```), the default configuration has a fallback to use ```gcc``` as standard C compiler when the CC environment variable is not set. Without proper patches to handle this situation, such configuration makes the building of any Lua module with parts written in C to fail, because LuaRocks tries to use ```gcc``` when it should use ```clang```.

There are two manners to reproduce this issue:

1. Installing things locally and try to install a Lua module written in C through LuaRocks yourself (I'm not going to cover it, because it involves a bit of knowledge about MSYS2).
2. Through a GitHub Action (recommended)

> [!TIP]
> 
> If you don't want to run yourself the steps in the expandable section in the end of this issue, just login on GitHub and browse how it ran on a custom branch that I created for the reproduction [https://github.com/luau-project/luarocks/actions/runs/13504448310/job/37730636032](https://github.com/luau-project/luarocks/actions/runs/13504448310/job/37730636032).

> [!NOTE]
> 
> I have also reported this issue downstream [https://github.com/msys2/MINGW-packages/issues/23493](https://github.com/msys2/MINGW-packages/issues/23493).

<details>

<summary>To reproduce yourself, expand here</summary>

Create a new branch on your fork, paste the following yml code on a file ```.github/workflows/msys2-cc-issue-repro.yml``` and push it

```yaml
name: MSYS2 Issue Reproduction

on: [push, pull_request]

jobs:
  msys2-issue-repro:
    runs-on: windows-latest
    
    defaults:
      run:
        shell: msys2 {0}
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64
          update: true
          install: |
            git
            mingw-w64-clang-x86_64-cc
            mingw-w64-clang-x86_64-lua-luarocks
      
      - name: Test the installation of LuaFileSystem
        run: luarocks install luafilesystem
```

</details>

---

**Edit**: the main post was edited (see [https://github.com/luarocks/luarocks/issues/1753#issuecomment-2679297515](https://github.com/luarocks/luarocks/issues/1753#issuecomment-2679297515))

**Comment by luau-project** [comment]
Thank you for the kind words. Hopefully, we'll find a solution for this issue together.

**Comment by luau-project** [comment]
## Update

Hi, I noticed a small issue in the GitHub workflow. The updated and correct workflow, as earlier, is in the expandable section in the end. However, the result is still the same.

> [!NOTE]
> 
> I'll edit the main post, to let people watching this issue to be informed.

* CI run [https://github.com/luau-project/luarocks/actions/runs/13504448310/job/37730636032](https://github.com/luau-project/luarocks/actions/runs/13504448310/job/37730636032).
* Screenshot

![Image](https://github.com/user-attachments/assets/1d572c74-99c7-48e6-bc9e-d48b7651583c)

<details>

<summary>To reproduce yourself, expand here</summary>

Create a new branch on your fork, paste the following yml code on a file ```.github/workflows/msys2-cc-issue-repro.yml``` and push it

```yaml
name: MSYS2 Issue Reproduction

on: [push, pull_request]

jobs:
  msys2-issue-repro:
    runs-on: windows-latest
    
    defaults:
      run:
        shell: msys2 {0}
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64
          update: true
          install: |
            git
            mingw-w64-clang-x86_64-cc
            mingw-w64-clang-x86_64-lua-luarocks
      
      - name: Test the installation of LuaFileSystem
        run: luarocks install luafilesystem
```

</details>
