### ISSUE TITLE
LuaRocks fails to uninstall LuaFileSystem and LuaSocket correctly on MSYS2

### ISSUE THREAD

**Issue by luau-project** [luarocks/luarocks#1755]
### Please fill out the following:
- **Platform:**
  - Windows

- **LuaRocks version:**
  - Even though the version of LuaRocks installed on MSYS2 repositories is 3.9.2, I have confirmed locally that this issue still applies to 3.11.1

- **LuaRocks output from when the issue occurred:**
  It can be clearly seen on the image that LuaRocks does not remove LuaFileSystem properly (DLL is still there)

> [!NOTE]
> 
> Locally, upgrading LuaRocks from 3.9.2 to 3.11.1 without additional patches except those provided by MSYS2, LuaRocks behaves like in the image below. The same behavior presented here was also verified for ```luasocket```, but I wanted to keep things simple and I decided to not include it in the reproduction below.

![Image](https://github.com/user-attachments/assets/ebb59d75-ca73-48ae-8432-eabca38f67fc)

- **Description:**

This issue is similar to [https://github.com/luarocks/luarocks/issues/1428](https://github.com/luarocks/luarocks/issues/1428). Even though this was supposed to be fixed by [https://github.com/luarocks/luarocks/pull/1616](https://github.com/luarocks/luarocks/pull/1616), this issue still persists on LuaRocks 3.11.1 after upgrading it manually on MSYS2.

There is not an easy way for me to show the reproduction of this issue for LuaRocks 3.11.1 on MSYS2, because I would scare you guys performing a complicated update from 3.9.2 to 3.11.1 through GitHub Actions. However, in order to give a feeling of what is happening, I decided to show the reproduction for LuaRocks 3.9.2. There are two manners to do that:

1. Installing things locally, install ```luafilesystem``` through LuaRocks yourself, then remove ```luafilesystem``` through LuaRocks. You'll notice that ```luafilesystem``` was not removed properly (I'm not going to cover it, because it involves a bit of knowledge about MSYS2).
2. Through a GitHub Action (recommended)

> [!TIP]
> 
> If you don't want to run yourself the steps in the expandable section in the end of this issue, just login on GitHub and browse how it ran on a custom branch that I created for the reproduction [https://github.com/luau-project/luarocks/actions/runs/13504293876/job/37730116907](https://github.com/luau-project/luarocks/actions/runs/13504293876/job/37730116907).

<details>

<summary>To reproduce yourself, expand here</summary>

Create a new branch on your fork, paste the following yml code on a file ```.github/workflows/msys2-uninstall-issue-repro.yml``` and push it

```yaml
name: MSYS2 Uninstall Issue Reproduction

on: [push, pull_request]

jobs:
  msys2-uninstall-issue-repro:
    runs-on: windows-latest
    
    defaults:
      run:
        shell: msys2 {0}
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: |
            git
            mingw-w64-ucrt-x86_64-cc
            mingw-w64-ucrt-x86_64-lua-luarocks
      
      - name: Install LuaFileSystem
        run: luarocks install luafilesystem
      
      - name: Remove LuaFileSystem
        run: luarocks remove luafilesystem

      - name: Show that LuaFileSystem can still be found by Lua
        run: lua -e "print(require('lfs'))"

      - name: Show that LuaFileSystem dll was not removed
        run: find ${MINGW_PREFIX}/lib/lua -type f -name "*.dll" 
```

</details>
